// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ClaimBased {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Label signedIn;
		
		protected System.Web.UI.WebControls.Label claimType;
		
		protected System.Web.UI.WebControls.Label claimValue;
		
		protected System.Web.UI.WebControls.Label claimValueType;
		
		protected System.Web.UI.WebControls.Label claimSubjectName;
		
		protected System.Web.UI.WebControls.Label claimIssuer;
	}
}
